# This is a sample plugin.yml
# For more information refer to http://wiki.bukkit.org/Plugin_YAML
main: edu.unca.szhang.Culd.Culd
name: ${project.name}
version: ${project.version}
author: ShuoZhang
description: ${project.description}
commands:
  culd:
    description: Culdcept spells
    usage: use [ /<culd> description ] for all available commands
    permission: culd.*
permissions:
  culd.*:
    description: gives all permissions of the Plugin
    default: true
    children:
      culd.description:
        description: explains all available commands         