# This is a sample plugin.yml
# For more information refer to http://wiki.bukkit.org/Plugin_YAML
main: edu.unca.szhang.Culd.Culd
name: ${project.name}
version: ${project.version}
author: ShuoZhang
description: ${project.description}
commands:
  culd:
    description: Culdcept spells
    usage: use [ /<culd> description ] for all available commands
    permission: culd.*
permissions:
  culd.*:
    description: gives all permissions of the Plugin
    default: true
    children:
      culd.description:
        description: explains all available commands
      culd.find:
        description: gives user an item
      culd.ruin:
        description: destroys all items in target inventory
      culd.hope:
        description: gives user two new items
      culd.upheaval:
        description: changes target terrain element to fire
      culd.sink:
        description: changes target terrain element to water
      culd.weathering:
        description: changes target terrain element to sand
      culd.growth:
        description: changes target terrain element to grass
      culd.subside:
        description: lowers target terrain by 1 level
      culd.omnipotent:
        description: Reveals current status of other players
      culd.blast:
        description: Deals 3 hearts of damage to target player
      culd.cure:
        description: Heals target player fully